### ISSUE TITLE
Create models

### ISSUE THREAD

**Issue by vctrodrigues** [vctrodrigues/wallet-java#2]
**What do we need to do?**

Create the application models.

----

**Implementation details**

- [x] Draw the entity relationship diagram
- [x] Create respective models using [this diagram](https://drive.google.com/file/d/1_L9y3GECTaCwQ8eE6GR7yJKQ6SCAYynA/view?usp=sharing) as a reference.
  - [x] User
  - [x] Transaction
  - [x] MoneyBox
  - [x] Expense
  - [x] TransactionType (enum)
  - [x] Currency (enum)
- [ ]  Update diagram

**Comment by fernandalaiss** [comment]
@vctrodrigues let me edit the diagram, please.
